export const WORDS = [
  "abelmosco", "abocado", "abordar", "abrazar", "abrigar", "abrir", "absoluto", "abundar", "abuso", "acabar",
  "acaece", "acceso", "accion", "acechar", "acelerar", "aceptar", "acerca", "acercar", "acompañar",
  "acordar", "acrecentar", "actitud", "actividad", "actual", "actuar", "acudir", "acuerdo", "adelante",
  "adivinar", "administrar", "adoptar", "adorar", "agarrar", "agregar", "agua", "ahogarse", "ahorrar",
  "aire", "aislar", "alcanzar", "alcoba", "aldea", "alegrar", "alegrìa", "algo", "alguien", "algùn",
  "aliviar", "alma", "alto", "altura", "amar", "amargo", "amarillo", "amasijo", "amateur", "ambiente",
  "amigo", "amor", "amplio", "analisis", "andar", "animal", "anoche", "ante", "anterior", "antiguo",
  "año", "añadir", "aparecer", "apenas", "aperturismo", "aplicar", "apoyar", "aprender", "aprovechar",
  "aqui", "arbol", "area", "arma", "armiño", "arte", "articulo", "artista", "asunto", "atender",
  "atencion", "atento", "ato", "atras", "atravesar", "atrever", "aumentar", "aunque", "autor", "autoridad",
  "auxilio", "avanzar", "ayer", "ayuda", "ayudar", "azota", "aztecar", "azul", "bailar", "bajar",
  "bajo", "banco", "base", "bastante", "bastar", "beber", "belleza", "bien", "bizcocho", "blanco",
  "boca", "brazo", "bueno", "buque", "buscar", "caballo", "cabeza", "cabo", "cada", "caer",
  "cajeta", "calle", "calor", "cama", "cambiar", "cambio", "camino", "campo", "cancelar", "canta",
  "cantar", "capacidad", "capaz", "capital", "capitan", "cara", "caracter", "carbon", "cargo", "carne",
  "carrera", "carta", "casa", "casar", "casi", "caso", "catedral", "causa", "cebar", "ceder",
  "celebrar", "celoso", "centrar", "centro", "cerca", "cero", "cerrar", "cielo", "ciencia", "cierto",
  "cinco", "ciudad", "claro", "clase", "coger", "cola", "color", "comer", "como", "compañero",
  "compañía", "completo", "comprar", "comprender", "comprension", "compromiso", "comun", "concebir", "concepto",
  "condicion", "conducir", "conocer", "conocimiento", "conseguir", "consejo", "considerar", "constitucion",
  "construir", "contar", "contemplar", "contener", "contento", "contestar", "contra", "contrario",
  "control", "convencer", "convenir", "convertir", "corazon", "correr", "corto", "cosa", "costa",
  "costar", "crear", "crecer", "creer", "criminal", "criterio", "cruz", "cual", "cualquier",
  "cuanto", "cuarto", "cuatro", "cubrir", "cuello", "cuenta", "cuerpo", "cuestion", "culpa", "cultura",
  "cumplir", "cumplir", "cuyo", "dar", "dato", "deber", "decaer", "decidir", "decir",
  "defender", "defensa", "dejar", "demas", "demonio", "dentra", "dentro", "derecho", "desafiar",
  "desaparecer", "desarrollo", "descubrir", "desde", "desear", "deseo", "despacio", "despues", "dia",
  "diferencia", "diferente", "dificil", "dinero", "direccion", "dirigir", "distinto", "doctor", "dolor",
  "donde", "dormir", "dos", "duda", "dueño", "dulce", "durante", "duro", "economia", "edad",
  "educar", "ejemplo", "ejercito", "ejercer", "eleccion", "elegir", "elemento", "ella", "embargo",
  "empezar", "empresa", "encontrar", "energia", "enfermo", "enorme", "enseñar", "entender", "entonces",
  "entrada", "entrar", "entre", "entregar", "epoca", "equipo", "error", "escena", "escribir",
  "escritor", "escuchar", "escuela", "eso", "espacio", "espada", "espalda", "esperar", "espesar",
  "espiritu", "estable", "estado", "estar", "este", "esto", "estrella", "estructura", "estudio",
  "estudiar", "etapa", "evitar", "exacto", "existir", "exito", "experiencia", "explicar", "expresar",
  "exterior", "extra", "facil", "falta", "faltar", "familia", "famoso", "favor", "fecha",
  "feliz", "feo", "fiebre", "fiesta", "figura", "fin", "final", "firma", "firmar", "fisica",
  "flaco", "flexible", "flor", "fluir", "fondo", "forma", "formar", "frente", "frio", "frito",
  "fuego", "fuente", "fuera", "fuerte", "fuerza", "funcion", "funcionar", "fundamental", "fusil", "futuro",
  "ganar", "ganas", "general", "gente", "gobierno", "golpe", "gracias", "grande", "grasa", "gratis",
  "grave", "gritar", "grito", "grueso", "grupo", "guardar", "guerra", "gustar", "haber", "habitacion",
  "hablar", "hacer", "hacia", "hallar", "hasta", "hecho", "herir", "hermano", "hierro", "hijo",
  "historia", "historico", "hombre", "hora", "hotel", "hoy", "humano", "humo", "idea", "iglesia",
  "igual", "imagen", "imaginar", "imponer", "importar", "importancia", "importante", "imposible", "impresion",
  "incluir", "indicar", "industria", "incluso", "informacion", "inmediato", "inmenso", "insistir", "intentar",
  "interes", "interesar", "interior", "internacional", "ir", "izquierdo", "jefe", "juego", "jugar",
  "junio", "junto", "joven", "joya", "juicio", "justicia", "justo", "juventud", "labio", "lado",
  "largo", "lectura", "leche", "leer", "lejos", "lengua", "lenguaje", "lento", "levantar", "ley",
  "libertad", "libre", "libre", "libro", "lider", "limite", "limpio", "linea", "llamar", "llegar",
  "llenar", "lleno", "llevar", "llorar", "llover", "lluvia", "local", "loco", "lograr", "lucha",
  "luchar", "luego", "lugar", "luz", "madre", "maestro", "magnetico", "mal", "malo", "mandar",
  "mando", "manera", "mano", "mantener", "mañana", "maquina", "mar", "marcar", "marcha", "marchar",
  "marido", "mas", "masa", "masacre", "matar", "material", "mayor", "media", "medida", "medir", "medio",
  "mejor", "memoria", "menor", "menos", "mensaje", "mente", "mente", "menudo", "mercado", "mes", "mesa",
  "meter", "metro", "miedo", "miembro", "mientras", "militar", "millon", "ministro", "minuto", "mirada",
  "mirar", "mismo", "mitad", "modelo", "moderno", "modo", "molino", "momento", "monte", "moral", "morir",
  "mostrar", "movil", "movimiento", "muchacho", "mucho", "muerte", "mujer", "mundo", "municipal", "musica",
  "muy", "nacer", "nacion", "nacional", "nada", "nadie", "natural", "naturaleza", "necesario",
  "necesidad", "necesitar", "negar", "negociar", "negocio", "negro", "ni", "ningun", "nivel",
  "nivel", "noche", "nombre", "normal", "norte", "nota", "notar", "noticia", "novela", "nube",
  "nuestro", "nuevo", "numero", "nunca", "nutricion", "obedecer", "objetivo", "objeto", "obligar",
  "obra", "observar", "obtener", "occidente", "ocho", "ocupar", "ocurrir", "oficial", "ofrecer", "oido",
  "oir", "ojo", "olvidar", "opinion", "orden", "organizar", "origen", "oro", "oscuro", "otro",
  "padre", "pagar", "pais", "pajaro", "palabra", "palacio", "pan", "papel", "par", "para",
  "pared", "parte", "particular", "partido", "partir", "pasado", "pasar", "pasear", "paso", "paz",
  "pecado", "pecho", "pedir", "pelear", "pelicula", "peligro", "pelo", "pena", "pensamiento", "pensar",
  "pequeño", "perder", "perfecto", "periodico", "periodo", "permitir", "pero", "perro", "persona",
  "personal", "pertenecer", "pesado", "pesar", "pesca", "pie", "piedra", "piel", "pierna",
  "pieza", "pintar", "pintura", "plan", "plano", "planta", "plata", "playa", "plaza",
  "pleno", "poblacion", "pobre", "poco", "poder", "poema", "poesia", "poeta", "policia",
  "politica", "politico", "polvo", "poner", "popular", "por", "porque", "posibilidad", "posible", "practica",
  "precio", "preciso", "preferir", "pregunta", "preguntar", "preocupar", "preparar", "presencia",
  "presentar", "presente", "presidente", "pretender", "primero", "principal", "principio", "prisa", "problema",
  "proceso", "producir", "producto", "profesion", "profesor", "profundo", "programa", "pronto", "propio",
  "proponer", "proteger", "protestar", "proveer", "proximo", "proyecto", "prueba", "publicar", "publico",
  "pueblo", "puerta", "pues", "puesto", "pulsera", "punto", "puro", "que", "quedar", "querer",
  "quien", "quitar", "radio", "raiz", "razon", "real", "realidad", "realizar", "realmente", "reclamar",
  "recoger", "reconocer", "recordar", "recorrer", "recruiting", "recto", "red", "referir", "region",
  "regla", "regresar", "regular", "reino", "relacion", "religion", "repetir", "representar", "republica",
  "requerir", "resistir", "resolver", "respecto", "responder", "respuesta", "resto", "resultado", "reunir", "rey",
  "rico", "rio", "ritmo", "robar", "robot", "roca", "rojo", "romper", "ronco", "rosa", "rostro",
  "saber", "sacar", "salida", "salir", "salud", "salvar", "sangre", "santo", "secreto", "sector",
  "sed", "seguir", "segun", "segundo", "seguridad", "seguro", "semana", "sencillo", "sentar", "sentido",
  "sentir", "señal", "señalar", "señor", "separar", "ser", "serio", "servicio", "servir", "si",
  "siempre", "significar", "siguiente", "silencio", "simple", "sin", "sino", "sistema", "sitio", "situacion",
  "sobre", "social", "sociedad", "sol", "soldado", "solo", "sombra", "someter", "sonar", "sonreir",
  "sonrisa", "soplar", "sorprender", "suave", "subir", "suceder", "suelo", "sueño", "suerte", "suficiente",
  "sufrir", "superar", "suponer", "suprimir", "sur", "surgir", "tal", "tambien", "tampoco", "tan",
  "tanto", "tarde", "tarea", "teatro", "tecnica", "tecnologia", "tema", "temer", "temor", "tender",
  "tener", "teoria", "tercero", "terminar", "termino", "tierra", "tipo", "tirar", "titulo", "tocar",
  "todavia", "todo", "tomar", "tono", "tonto", "total", "trabajar", "trabajo", "tradicion", "traducir",
  "traer", "tratar", "traves", "tres", "triste", "triunfo", "tu", "tubo", "unico", "unir",
  "universidad", "uno", "usar", "uso", "usted", "usual", "util", "utilizar", "vago", "valer",
  "valiente", "valor", "varios", "veces", "vecino", "vender", "venir", "ventana", "ventaja", "ver",
  "verano", "verdad", "verdadero", "verde", "verso", "vestir", "vez", "via", "viaje", "viajar",
  "vicente", "vida", "viejo", "viento", "violencia", "virtud", "vista", "vivir", "vivo", "volver",
  "voto", "voz", "vuelo", "ya", "yo", "zona", "zorro"
]

export function getRandomWord() {
  return WORDS[Math.floor(Math.random() * WORDS.length)]
}